// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1/build.proto

package v1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type BuildRun struct {
	Spec                 *BuildSpec      `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Config               *BuildRunConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BuildRun) Reset()         { *m = BuildRun{} }
func (m *BuildRun) String() string { return proto.CompactTextString(m) }
func (*BuildRun) ProtoMessage()    {}
func (*BuildRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{0}
}
func (m *BuildRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRun.Unmarshal(m, b)
}
func (m *BuildRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRun.Marshal(b, m, deterministic)
}
func (m *BuildRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRun.Merge(m, src)
}
func (m *BuildRun) XXX_Size() int {
	return xxx_messageInfo_BuildRun.Size(m)
}
func (m *BuildRun) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRun.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRun proto.InternalMessageInfo

func (m *BuildRun) GetSpec() *BuildSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *BuildRun) GetConfig() *BuildRunConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// This contains a few extra things at build time
type BuildRunConfig struct {
	BuildEnvVars         *BuildEnvVars      `protobuf:"bytes,1,opt,name=build_env_vars,json=buildEnvVars,proto3" json:"build_env_vars,omitempty"`
	ComputedBuildVars    *ComputedBuildVars `protobuf:"bytes,2,opt,name=computed_build_vars,json=computedBuildVars,proto3" json:"computed_build_vars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BuildRunConfig) Reset()         { *m = BuildRunConfig{} }
func (m *BuildRunConfig) String() string { return proto.CompactTextString(m) }
func (*BuildRunConfig) ProtoMessage()    {}
func (*BuildRunConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{1}
}
func (m *BuildRunConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRunConfig.Unmarshal(m, b)
}
func (m *BuildRunConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRunConfig.Marshal(b, m, deterministic)
}
func (m *BuildRunConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRunConfig.Merge(m, src)
}
func (m *BuildRunConfig) XXX_Size() int {
	return xxx_messageInfo_BuildRunConfig.Size(m)
}
func (m *BuildRunConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRunConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRunConfig proto.InternalMessageInfo

func (m *BuildRunConfig) GetBuildEnvVars() *BuildEnvVars {
	if m != nil {
		return m.BuildEnvVars
	}
	return nil
}

func (m *BuildRunConfig) GetComputedBuildVars() *ComputedBuildVars {
	if m != nil {
		return m.ComputedBuildVars
	}
	return nil
}

type BuildEnvVars struct {
	BuildId              string   `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	CommitSha            string   `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	TagVersion           string   `protobuf:"bytes,3,opt,name=tag_version,json=tagVersion,proto3" json:"tag_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildEnvVars) Reset()         { *m = BuildEnvVars{} }
func (m *BuildEnvVars) String() string { return proto.CompactTextString(m) }
func (*BuildEnvVars) ProtoMessage()    {}
func (*BuildEnvVars) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{2}
}
func (m *BuildEnvVars) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildEnvVars.Unmarshal(m, b)
}
func (m *BuildEnvVars) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildEnvVars.Marshal(b, m, deterministic)
}
func (m *BuildEnvVars) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildEnvVars.Merge(m, src)
}
func (m *BuildEnvVars) XXX_Size() int {
	return xxx_messageInfo_BuildEnvVars.Size(m)
}
func (m *BuildEnvVars) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildEnvVars.DiscardUnknown(m)
}

var xxx_messageInfo_BuildEnvVars proto.InternalMessageInfo

func (m *BuildEnvVars) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *BuildEnvVars) GetCommitSha() string {
	if m != nil {
		return m.CommitSha
	}
	return ""
}

func (m *BuildEnvVars) GetTagVersion() string {
	if m != nil {
		return m.TagVersion
	}
	return ""
}

type ComputedBuildVars struct {
	Release              bool     `protobuf:"varint,1,opt,name=release,proto3" json:"release,omitempty"`
	ImageTag             string   `protobuf:"bytes,2,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputedBuildVars) Reset()         { *m = ComputedBuildVars{} }
func (m *ComputedBuildVars) String() string { return proto.CompactTextString(m) }
func (*ComputedBuildVars) ProtoMessage()    {}
func (*ComputedBuildVars) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{3}
}
func (m *ComputedBuildVars) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputedBuildVars.Unmarshal(m, b)
}
func (m *ComputedBuildVars) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputedBuildVars.Marshal(b, m, deterministic)
}
func (m *ComputedBuildVars) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputedBuildVars.Merge(m, src)
}
func (m *ComputedBuildVars) XXX_Size() int {
	return xxx_messageInfo_ComputedBuildVars.Size(m)
}
func (m *ComputedBuildVars) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputedBuildVars.DiscardUnknown(m)
}

var xxx_messageInfo_ComputedBuildVars proto.InternalMessageInfo

func (m *ComputedBuildVars) GetRelease() bool {
	if m != nil {
		return m.Release
	}
	return false
}

func (m *ComputedBuildVars) GetImageTag() string {
	if m != nil {
		return m.ImageTag
	}
	return ""
}

type GcloudConfig struct {
	ProjectId      string `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DecryptKey     string `protobuf:"bytes,5,opt,name=decrypt_key,json=decryptKey,proto3" json:"decrypt_key,omitempty"`
	DecryptKeyring string `protobuf:"bytes,6,opt,name=decrypt_keyring,json=decryptKeyring,proto3" json:"decrypt_keyring,omitempty"`
	// optional location to put helm charts
	HelmChartBucket      string   `protobuf:"bytes,7,opt,name=helm_chart_bucket,json=helmChartBucket,proto3" json:"helm_chart_bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GcloudConfig) Reset()         { *m = GcloudConfig{} }
func (m *GcloudConfig) String() string { return proto.CompactTextString(m) }
func (*GcloudConfig) ProtoMessage()    {}
func (*GcloudConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{4}
}
func (m *GcloudConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcloudConfig.Unmarshal(m, b)
}
func (m *GcloudConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcloudConfig.Marshal(b, m, deterministic)
}
func (m *GcloudConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcloudConfig.Merge(m, src)
}
func (m *GcloudConfig) XXX_Size() int {
	return xxx_messageInfo_GcloudConfig.Size(m)
}
func (m *GcloudConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GcloudConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GcloudConfig proto.InternalMessageInfo

func (m *GcloudConfig) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GcloudConfig) GetDecryptKey() string {
	if m != nil {
		return m.DecryptKey
	}
	return ""
}

func (m *GcloudConfig) GetDecryptKeyring() string {
	if m != nil {
		return m.DecryptKeyring
	}
	return ""
}

func (m *GcloudConfig) GetHelmChartBucket() string {
	if m != nil {
		return m.HelmChartBucket
	}
	return ""
}

// This gets checked into project repo
type BuildSpec struct {
	Config               *BuildConfig  `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Checks               []*Check      `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	Manifests            []*Manifest   `protobuf:"bytes,3,rep,name=manifests,proto3" json:"manifests,omitempty"`
	Compile              []*Compile    `protobuf:"bytes,4,rep,name=compile,proto3" json:"compile,omitempty"`
	TestRuns             []*TestRun    `protobuf:"bytes,5,rep,name=test_runs,json=testRuns,proto3" json:"test_runs,omitempty"`
	Containers           []*Container  `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`
	Docs                 *Docs         `protobuf:"bytes,7,opt,name=docs,proto3" json:"docs,omitempty"`
	Distribution         *Distribution `protobuf:"bytes,8,opt,name=distribution,proto3" json:"distribution,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BuildSpec) Reset()         { *m = BuildSpec{} }
func (m *BuildSpec) String() string { return proto.CompactTextString(m) }
func (*BuildSpec) ProtoMessage()    {}
func (*BuildSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{5}
}
func (m *BuildSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildSpec.Unmarshal(m, b)
}
func (m *BuildSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildSpec.Marshal(b, m, deterministic)
}
func (m *BuildSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildSpec.Merge(m, src)
}
func (m *BuildSpec) XXX_Size() int {
	return xxx_messageInfo_BuildSpec.Size(m)
}
func (m *BuildSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildSpec.DiscardUnknown(m)
}

var xxx_messageInfo_BuildSpec proto.InternalMessageInfo

func (m *BuildSpec) GetConfig() *BuildConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *BuildSpec) GetChecks() []*Check {
	if m != nil {
		return m.Checks
	}
	return nil
}

func (m *BuildSpec) GetManifests() []*Manifest {
	if m != nil {
		return m.Manifests
	}
	return nil
}

func (m *BuildSpec) GetCompile() []*Compile {
	if m != nil {
		return m.Compile
	}
	return nil
}

func (m *BuildSpec) GetTestRuns() []*TestRun {
	if m != nil {
		return m.TestRuns
	}
	return nil
}

func (m *BuildSpec) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *BuildSpec) GetDocs() *Docs {
	if m != nil {
		return m.Docs
	}
	return nil
}

func (m *BuildSpec) GetDistribution() *Distribution {
	if m != nil {
		return m.Distribution
	}
	return nil
}

type Manifest struct {
	// Types that are valid to be assigned to Manifest:
	//	*Manifest_Helm
	Manifest             isManifest_Manifest `protobuf_oneof:"manifest"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Manifest) Reset()         { *m = Manifest{} }
func (m *Manifest) String() string { return proto.CompactTextString(m) }
func (*Manifest) ProtoMessage()    {}
func (*Manifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{6}
}
func (m *Manifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manifest.Unmarshal(m, b)
}
func (m *Manifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manifest.Marshal(b, m, deterministic)
}
func (m *Manifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manifest.Merge(m, src)
}
func (m *Manifest) XXX_Size() int {
	return xxx_messageInfo_Manifest.Size(m)
}
func (m *Manifest) XXX_DiscardUnknown() {
	xxx_messageInfo_Manifest.DiscardUnknown(m)
}

var xxx_messageInfo_Manifest proto.InternalMessageInfo

type isManifest_Manifest interface {
	isManifest_Manifest()
}

type Manifest_Helm struct {
	Helm *HelmChart `protobuf:"bytes,1,opt,name=helm,proto3,oneof"`
}

func (*Manifest_Helm) isManifest_Manifest() {}

func (m *Manifest) GetManifest() isManifest_Manifest {
	if m != nil {
		return m.Manifest
	}
	return nil
}

func (m *Manifest) GetHelm() *HelmChart {
	if x, ok := m.GetManifest().(*Manifest_Helm); ok {
		return x.Helm
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Manifest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Manifest_OneofMarshaler, _Manifest_OneofUnmarshaler, _Manifest_OneofSizer, []interface{}{
		(*Manifest_Helm)(nil),
	}
}

func _Manifest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Manifest)
	// manifest
	switch x := m.Manifest.(type) {
	case *Manifest_Helm:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Helm); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Manifest.Manifest has unexpected type %T", x)
	}
	return nil
}

func _Manifest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Manifest)
	switch tag {
	case 1: // manifest.helm
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HelmChart)
		err := b.DecodeMessage(msg)
		m.Manifest = &Manifest_Helm{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Manifest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Manifest)
	// manifest
	switch x := m.Manifest.(type) {
	case *Manifest_Helm:
		s := proto.Size(x.Helm)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HelmChart struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UploadYamlToGithub   bool     `protobuf:"varint,2,opt,name=upload_yaml_to_github,json=uploadYamlToGithub,proto3" json:"upload_yaml_to_github,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelmChart) Reset()         { *m = HelmChart{} }
func (m *HelmChart) String() string { return proto.CompactTextString(m) }
func (*HelmChart) ProtoMessage()    {}
func (*HelmChart) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{7}
}
func (m *HelmChart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelmChart.Unmarshal(m, b)
}
func (m *HelmChart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelmChart.Marshal(b, m, deterministic)
}
func (m *HelmChart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelmChart.Merge(m, src)
}
func (m *HelmChart) XXX_Size() int {
	return xxx_messageInfo_HelmChart.Size(m)
}
func (m *HelmChart) XXX_DiscardUnknown() {
	xxx_messageInfo_HelmChart.DiscardUnknown(m)
}

var xxx_messageInfo_HelmChart proto.InternalMessageInfo

func (m *HelmChart) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelmChart) GetUploadYamlToGithub() bool {
	if m != nil {
		return m.UploadYamlToGithub
	}
	return false
}

type GoCompile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EntryPoint           string   `protobuf:"bytes,2,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Platforms            []string `protobuf:"bytes,3,rep,name=platforms,proto3" json:"platforms,omitempty"`
	UploadToGithub       bool     `protobuf:"varint,4,opt,name=upload_to_github,json=uploadToGithub,proto3" json:"upload_to_github,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoCompile) Reset()         { *m = GoCompile{} }
func (m *GoCompile) String() string { return proto.CompactTextString(m) }
func (*GoCompile) ProtoMessage()    {}
func (*GoCompile) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{8}
}
func (m *GoCompile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoCompile.Unmarshal(m, b)
}
func (m *GoCompile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoCompile.Marshal(b, m, deterministic)
}
func (m *GoCompile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoCompile.Merge(m, src)
}
func (m *GoCompile) XXX_Size() int {
	return xxx_messageInfo_GoCompile.Size(m)
}
func (m *GoCompile) XXX_DiscardUnknown() {
	xxx_messageInfo_GoCompile.DiscardUnknown(m)
}

var xxx_messageInfo_GoCompile proto.InternalMessageInfo

func (m *GoCompile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GoCompile) GetEntryPoint() string {
	if m != nil {
		return m.EntryPoint
	}
	return ""
}

func (m *GoCompile) GetPlatforms() []string {
	if m != nil {
		return m.Platforms
	}
	return nil
}

func (m *GoCompile) GetUploadToGithub() bool {
	if m != nil {
		return m.UploadToGithub
	}
	return false
}

type Compile struct {
	GoCompile            []*GoCompile `protobuf:"bytes,1,rep,name=go_compile,json=goCompile,proto3" json:"go_compile,omitempty"`
	YarnCompile          *YarnCompile `protobuf:"bytes,2,opt,name=yarn_compile,json=yarnCompile,proto3" json:"yarn_compile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Compile) Reset()         { *m = Compile{} }
func (m *Compile) String() string { return proto.CompactTextString(m) }
func (*Compile) ProtoMessage()    {}
func (*Compile) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{9}
}
func (m *Compile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Compile.Unmarshal(m, b)
}
func (m *Compile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Compile.Marshal(b, m, deterministic)
}
func (m *Compile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Compile.Merge(m, src)
}
func (m *Compile) XXX_Size() int {
	return xxx_messageInfo_Compile.Size(m)
}
func (m *Compile) XXX_DiscardUnknown() {
	xxx_messageInfo_Compile.DiscardUnknown(m)
}

var xxx_messageInfo_Compile proto.InternalMessageInfo

func (m *Compile) GetGoCompile() []*GoCompile {
	if m != nil {
		return m.GoCompile
	}
	return nil
}

func (m *Compile) GetYarnCompile() *YarnCompile {
	if m != nil {
		return m.YarnCompile
	}
	return nil
}

type YarnCompile struct {
	Directory            string   `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YarnCompile) Reset()         { *m = YarnCompile{} }
func (m *YarnCompile) String() string { return proto.CompactTextString(m) }
func (*YarnCompile) ProtoMessage()    {}
func (*YarnCompile) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{10}
}
func (m *YarnCompile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YarnCompile.Unmarshal(m, b)
}
func (m *YarnCompile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YarnCompile.Marshal(b, m, deterministic)
}
func (m *YarnCompile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YarnCompile.Merge(m, src)
}
func (m *YarnCompile) XXX_Size() int {
	return xxx_messageInfo_YarnCompile.Size(m)
}
func (m *YarnCompile) XXX_DiscardUnknown() {
	xxx_messageInfo_YarnCompile.DiscardUnknown(m)
}

var xxx_messageInfo_YarnCompile proto.InternalMessageInfo

func (m *YarnCompile) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

type Container struct {
	ImageName            string   `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	DockerFile           string   `protobuf:"bytes,2,opt,name=docker_file,json=dockerFile,proto3" json:"docker_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{11}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *Container) GetDockerFile() string {
	if m != nil {
		return m.DockerFile
	}
	return ""
}

type BuildConfig struct {
	RepoOrg         string `protobuf:"bytes,1,opt,name=repo_org,json=repoOrg,proto3" json:"repo_org,omitempty"`
	RepoName        string `protobuf:"bytes,2,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	OutputDirectory string `protobuf:"bytes,3,opt,name=output_directory,json=outputDirectory,proto3" json:"output_directory,omitempty"`
	VersionVar      string `protobuf:"bytes,4,opt,name=version_var,json=versionVar,proto3" json:"version_var,omitempty"`
	// Types that are valid to be assigned to CiConfig:
	//	*BuildConfig_Gcloud
	CiConfig             isBuildConfig_CiConfig `protobuf_oneof:"ci_config"`
	ContainerRegistries  []*ContainerRegistry   `protobuf:"bytes,20,rep,name=container_registries,json=containerRegistries,proto3" json:"container_registries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BuildConfig) Reset()         { *m = BuildConfig{} }
func (m *BuildConfig) String() string { return proto.CompactTextString(m) }
func (*BuildConfig) ProtoMessage()    {}
func (*BuildConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{12}
}
func (m *BuildConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildConfig.Unmarshal(m, b)
}
func (m *BuildConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildConfig.Marshal(b, m, deterministic)
}
func (m *BuildConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildConfig.Merge(m, src)
}
func (m *BuildConfig) XXX_Size() int {
	return xxx_messageInfo_BuildConfig.Size(m)
}
func (m *BuildConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuildConfig proto.InternalMessageInfo

type isBuildConfig_CiConfig interface {
	isBuildConfig_CiConfig()
}

type BuildConfig_Gcloud struct {
	Gcloud *GcloudConfig `protobuf:"bytes,10,opt,name=gcloud,proto3,oneof"`
}

func (*BuildConfig_Gcloud) isBuildConfig_CiConfig() {}

func (m *BuildConfig) GetCiConfig() isBuildConfig_CiConfig {
	if m != nil {
		return m.CiConfig
	}
	return nil
}

func (m *BuildConfig) GetRepoOrg() string {
	if m != nil {
		return m.RepoOrg
	}
	return ""
}

func (m *BuildConfig) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *BuildConfig) GetOutputDirectory() string {
	if m != nil {
		return m.OutputDirectory
	}
	return ""
}

func (m *BuildConfig) GetVersionVar() string {
	if m != nil {
		return m.VersionVar
	}
	return ""
}

func (m *BuildConfig) GetGcloud() *GcloudConfig {
	if x, ok := m.GetCiConfig().(*BuildConfig_Gcloud); ok {
		return x.Gcloud
	}
	return nil
}

func (m *BuildConfig) GetContainerRegistries() []*ContainerRegistry {
	if m != nil {
		return m.ContainerRegistries
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BuildConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BuildConfig_OneofMarshaler, _BuildConfig_OneofUnmarshaler, _BuildConfig_OneofSizer, []interface{}{
		(*BuildConfig_Gcloud)(nil),
	}
}

func _BuildConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BuildConfig)
	// ci_config
	switch x := m.CiConfig.(type) {
	case *BuildConfig_Gcloud:
		_ = b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Gcloud); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BuildConfig.CiConfig has unexpected type %T", x)
	}
	return nil
}

func _BuildConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BuildConfig)
	switch tag {
	case 10: // ci_config.gcloud
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GcloudConfig)
		err := b.DecodeMessage(msg)
		m.CiConfig = &BuildConfig_Gcloud{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BuildConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BuildConfig)
	// ci_config
	switch x := m.CiConfig.(type) {
	case *BuildConfig_Gcloud:
		s := proto.Size(x.Gcloud)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ContainerRegistry struct {
	BaseUrl     string `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ReleaseOnly bool   `protobuf:"varint,2,opt,name=release_only,json=releaseOnly,proto3" json:"release_only,omitempty"`
	// Types that are valid to be assigned to Registry:
	//	*ContainerRegistry_Quay
	//	*ContainerRegistry_DockerHub
	//	*ContainerRegistry_Gcr
	Registry             isContainerRegistry_Registry `protobuf_oneof:"registry"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ContainerRegistry) Reset()         { *m = ContainerRegistry{} }
func (m *ContainerRegistry) String() string { return proto.CompactTextString(m) }
func (*ContainerRegistry) ProtoMessage()    {}
func (*ContainerRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{13}
}
func (m *ContainerRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRegistry.Unmarshal(m, b)
}
func (m *ContainerRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRegistry.Marshal(b, m, deterministic)
}
func (m *ContainerRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRegistry.Merge(m, src)
}
func (m *ContainerRegistry) XXX_Size() int {
	return xxx_messageInfo_ContainerRegistry.Size(m)
}
func (m *ContainerRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRegistry proto.InternalMessageInfo

type isContainerRegistry_Registry interface {
	isContainerRegistry_Registry()
}

type ContainerRegistry_Quay struct {
	Quay *QuayRegistry `protobuf:"bytes,10,opt,name=quay,proto3,oneof"`
}
type ContainerRegistry_DockerHub struct {
	DockerHub *DockerHubRegistry `protobuf:"bytes,11,opt,name=docker_hub,json=dockerHub,proto3,oneof"`
}
type ContainerRegistry_Gcr struct {
	Gcr *GoogleContainerRegistry `protobuf:"bytes,12,opt,name=gcr,proto3,oneof"`
}

func (*ContainerRegistry_Quay) isContainerRegistry_Registry()      {}
func (*ContainerRegistry_DockerHub) isContainerRegistry_Registry() {}
func (*ContainerRegistry_Gcr) isContainerRegistry_Registry()       {}

func (m *ContainerRegistry) GetRegistry() isContainerRegistry_Registry {
	if m != nil {
		return m.Registry
	}
	return nil
}

func (m *ContainerRegistry) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *ContainerRegistry) GetReleaseOnly() bool {
	if m != nil {
		return m.ReleaseOnly
	}
	return false
}

func (m *ContainerRegistry) GetQuay() *QuayRegistry {
	if x, ok := m.GetRegistry().(*ContainerRegistry_Quay); ok {
		return x.Quay
	}
	return nil
}

func (m *ContainerRegistry) GetDockerHub() *DockerHubRegistry {
	if x, ok := m.GetRegistry().(*ContainerRegistry_DockerHub); ok {
		return x.DockerHub
	}
	return nil
}

func (m *ContainerRegistry) GetGcr() *GoogleContainerRegistry {
	if x, ok := m.GetRegistry().(*ContainerRegistry_Gcr); ok {
		return x.Gcr
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ContainerRegistry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ContainerRegistry_OneofMarshaler, _ContainerRegistry_OneofUnmarshaler, _ContainerRegistry_OneofSizer, []interface{}{
		(*ContainerRegistry_Quay)(nil),
		(*ContainerRegistry_DockerHub)(nil),
		(*ContainerRegistry_Gcr)(nil),
	}
}

func _ContainerRegistry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ContainerRegistry)
	// registry
	switch x := m.Registry.(type) {
	case *ContainerRegistry_Quay:
		_ = b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Quay); err != nil {
			return err
		}
	case *ContainerRegistry_DockerHub:
		_ = b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DockerHub); err != nil {
			return err
		}
	case *ContainerRegistry_Gcr:
		_ = b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Gcr); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ContainerRegistry.Registry has unexpected type %T", x)
	}
	return nil
}

func _ContainerRegistry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ContainerRegistry)
	switch tag {
	case 10: // registry.quay
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(QuayRegistry)
		err := b.DecodeMessage(msg)
		m.Registry = &ContainerRegistry_Quay{msg}
		return true, err
	case 11: // registry.docker_hub
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DockerHubRegistry)
		err := b.DecodeMessage(msg)
		m.Registry = &ContainerRegistry_DockerHub{msg}
		return true, err
	case 12: // registry.gcr
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoogleContainerRegistry)
		err := b.DecodeMessage(msg)
		m.Registry = &ContainerRegistry_Gcr{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ContainerRegistry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ContainerRegistry)
	// registry
	switch x := m.Registry.(type) {
	case *ContainerRegistry_Quay:
		s := proto.Size(x.Quay)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ContainerRegistry_DockerHub:
		s := proto.Size(x.DockerHub)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ContainerRegistry_Gcr:
		s := proto.Size(x.Gcr)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type QuayRegistry struct {
	EncryptedToken       string   `protobuf:"bytes,1,opt,name=encrypted_token,json=encryptedToken,proto3" json:"encrypted_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuayRegistry) Reset()         { *m = QuayRegistry{} }
func (m *QuayRegistry) String() string { return proto.CompactTextString(m) }
func (*QuayRegistry) ProtoMessage()    {}
func (*QuayRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{14}
}
func (m *QuayRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuayRegistry.Unmarshal(m, b)
}
func (m *QuayRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuayRegistry.Marshal(b, m, deterministic)
}
func (m *QuayRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuayRegistry.Merge(m, src)
}
func (m *QuayRegistry) XXX_Size() int {
	return xxx_messageInfo_QuayRegistry.Size(m)
}
func (m *QuayRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_QuayRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_QuayRegistry proto.InternalMessageInfo

func (m *QuayRegistry) GetEncryptedToken() string {
	if m != nil {
		return m.EncryptedToken
	}
	return ""
}

type DockerHubRegistry struct {
	EncryptedToken       string   `protobuf:"bytes,1,opt,name=encrypted_token,json=encryptedToken,proto3" json:"encrypted_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockerHubRegistry) Reset()         { *m = DockerHubRegistry{} }
func (m *DockerHubRegistry) String() string { return proto.CompactTextString(m) }
func (*DockerHubRegistry) ProtoMessage()    {}
func (*DockerHubRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{15}
}
func (m *DockerHubRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockerHubRegistry.Unmarshal(m, b)
}
func (m *DockerHubRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockerHubRegistry.Marshal(b, m, deterministic)
}
func (m *DockerHubRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockerHubRegistry.Merge(m, src)
}
func (m *DockerHubRegistry) XXX_Size() int {
	return xxx_messageInfo_DockerHubRegistry.Size(m)
}
func (m *DockerHubRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_DockerHubRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_DockerHubRegistry proto.InternalMessageInfo

func (m *DockerHubRegistry) GetEncryptedToken() string {
	if m != nil {
		return m.EncryptedToken
	}
	return ""
}

type GoogleContainerRegistry struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleContainerRegistry) Reset()         { *m = GoogleContainerRegistry{} }
func (m *GoogleContainerRegistry) String() string { return proto.CompactTextString(m) }
func (*GoogleContainerRegistry) ProtoMessage()    {}
func (*GoogleContainerRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{16}
}
func (m *GoogleContainerRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleContainerRegistry.Unmarshal(m, b)
}
func (m *GoogleContainerRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleContainerRegistry.Marshal(b, m, deterministic)
}
func (m *GoogleContainerRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleContainerRegistry.Merge(m, src)
}
func (m *GoogleContainerRegistry) XXX_Size() int {
	return xxx_messageInfo_GoogleContainerRegistry.Size(m)
}
func (m *GoogleContainerRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleContainerRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleContainerRegistry proto.InternalMessageInfo

type TestRun struct {
	Args                 []string          `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Env                  map[string]string `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TestRun) Reset()         { *m = TestRun{} }
func (m *TestRun) String() string { return proto.CompactTextString(m) }
func (*TestRun) ProtoMessage()    {}
func (*TestRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{17}
}
func (m *TestRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRun.Unmarshal(m, b)
}
func (m *TestRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRun.Marshal(b, m, deterministic)
}
func (m *TestRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRun.Merge(m, src)
}
func (m *TestRun) XXX_Size() int {
	return xxx_messageInfo_TestRun.Size(m)
}
func (m *TestRun) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRun.DiscardUnknown(m)
}

var xxx_messageInfo_TestRun proto.InternalMessageInfo

func (m *TestRun) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *TestRun) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

type CodeGeneration struct {
	Entrypoint           string   `protobuf:"bytes,1,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeGeneration) Reset()         { *m = CodeGeneration{} }
func (m *CodeGeneration) String() string { return proto.CompactTextString(m) }
func (*CodeGeneration) ProtoMessage()    {}
func (*CodeGeneration) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{18}
}
func (m *CodeGeneration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeGeneration.Unmarshal(m, b)
}
func (m *CodeGeneration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeGeneration.Marshal(b, m, deterministic)
}
func (m *CodeGeneration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeGeneration.Merge(m, src)
}
func (m *CodeGeneration) XXX_Size() int {
	return xxx_messageInfo_CodeGeneration.Size(m)
}
func (m *CodeGeneration) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeGeneration.DiscardUnknown(m)
}

var xxx_messageInfo_CodeGeneration proto.InternalMessageInfo

func (m *CodeGeneration) GetEntrypoint() string {
	if m != nil {
		return m.Entrypoint
	}
	return ""
}

type SoloKitGeneration struct {
	MakeDependencies     []string `protobuf:"bytes,2,rep,name=make_dependencies,json=makeDependencies,proto3" json:"make_dependencies,omitempty"`
	GopathDependencies   []string `protobuf:"bytes,3,rep,name=gopath_dependencies,json=gopathDependencies,proto3" json:"gopath_dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoloKitGeneration) Reset()         { *m = SoloKitGeneration{} }
func (m *SoloKitGeneration) String() string { return proto.CompactTextString(m) }
func (*SoloKitGeneration) ProtoMessage()    {}
func (*SoloKitGeneration) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{19}
}
func (m *SoloKitGeneration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoloKitGeneration.Unmarshal(m, b)
}
func (m *SoloKitGeneration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoloKitGeneration.Marshal(b, m, deterministic)
}
func (m *SoloKitGeneration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoloKitGeneration.Merge(m, src)
}
func (m *SoloKitGeneration) XXX_Size() int {
	return xxx_messageInfo_SoloKitGeneration.Size(m)
}
func (m *SoloKitGeneration) XXX_DiscardUnknown() {
	xxx_messageInfo_SoloKitGeneration.DiscardUnknown(m)
}

var xxx_messageInfo_SoloKitGeneration proto.InternalMessageInfo

func (m *SoloKitGeneration) GetMakeDependencies() []string {
	if m != nil {
		return m.MakeDependencies
	}
	return nil
}

func (m *SoloKitGeneration) GetGopathDependencies() []string {
	if m != nil {
		return m.GopathDependencies
	}
	return nil
}

type Check struct {
	// Types that are valid to be assigned to Check:
	//	*Check_SoloKitGeneration
	//	*Check_CodeGeneration
	//	*Check_CheckFormat
	//	*Check_CheckSpelling
	Check                isCheck_Check `protobuf_oneof:"check"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Check) Reset()         { *m = Check{} }
func (m *Check) String() string { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()    {}
func (*Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{20}
}
func (m *Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Check.Unmarshal(m, b)
}
func (m *Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Check.Marshal(b, m, deterministic)
}
func (m *Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Check.Merge(m, src)
}
func (m *Check) XXX_Size() int {
	return xxx_messageInfo_Check.Size(m)
}
func (m *Check) XXX_DiscardUnknown() {
	xxx_messageInfo_Check.DiscardUnknown(m)
}

var xxx_messageInfo_Check proto.InternalMessageInfo

type isCheck_Check interface {
	isCheck_Check()
}

type Check_SoloKitGeneration struct {
	SoloKitGeneration *SoloKitGeneration `protobuf:"bytes,1,opt,name=solo_kit_generation,json=soloKitGeneration,proto3,oneof"`
}
type Check_CodeGeneration struct {
	CodeGeneration *CodeGeneration `protobuf:"bytes,2,opt,name=code_generation,json=codeGeneration,proto3,oneof"`
}
type Check_CheckFormat struct {
	CheckFormat *CheckFormat `protobuf:"bytes,3,opt,name=check_format,json=checkFormat,proto3,oneof"`
}
type Check_CheckSpelling struct {
	CheckSpelling *CheckSpelling `protobuf:"bytes,4,opt,name=check_spelling,json=checkSpelling,proto3,oneof"`
}

func (*Check_SoloKitGeneration) isCheck_Check() {}
func (*Check_CodeGeneration) isCheck_Check()    {}
func (*Check_CheckFormat) isCheck_Check()       {}
func (*Check_CheckSpelling) isCheck_Check()     {}

func (m *Check) GetCheck() isCheck_Check {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *Check) GetSoloKitGeneration() *SoloKitGeneration {
	if x, ok := m.GetCheck().(*Check_SoloKitGeneration); ok {
		return x.SoloKitGeneration
	}
	return nil
}

func (m *Check) GetCodeGeneration() *CodeGeneration {
	if x, ok := m.GetCheck().(*Check_CodeGeneration); ok {
		return x.CodeGeneration
	}
	return nil
}

func (m *Check) GetCheckFormat() *CheckFormat {
	if x, ok := m.GetCheck().(*Check_CheckFormat); ok {
		return x.CheckFormat
	}
	return nil
}

func (m *Check) GetCheckSpelling() *CheckSpelling {
	if x, ok := m.GetCheck().(*Check_CheckSpelling); ok {
		return x.CheckSpelling
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Check) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Check_OneofMarshaler, _Check_OneofUnmarshaler, _Check_OneofSizer, []interface{}{
		(*Check_SoloKitGeneration)(nil),
		(*Check_CodeGeneration)(nil),
		(*Check_CheckFormat)(nil),
		(*Check_CheckSpelling)(nil),
	}
}

func _Check_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Check)
	// check
	switch x := m.Check.(type) {
	case *Check_SoloKitGeneration:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SoloKitGeneration); err != nil {
			return err
		}
	case *Check_CodeGeneration:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CodeGeneration); err != nil {
			return err
		}
	case *Check_CheckFormat:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CheckFormat); err != nil {
			return err
		}
	case *Check_CheckSpelling:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CheckSpelling); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Check.Check has unexpected type %T", x)
	}
	return nil
}

func _Check_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Check)
	switch tag {
	case 1: // check.solo_kit_generation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SoloKitGeneration)
		err := b.DecodeMessage(msg)
		m.Check = &Check_SoloKitGeneration{msg}
		return true, err
	case 2: // check.code_generation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CodeGeneration)
		err := b.DecodeMessage(msg)
		m.Check = &Check_CodeGeneration{msg}
		return true, err
	case 3: // check.check_format
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CheckFormat)
		err := b.DecodeMessage(msg)
		m.Check = &Check_CheckFormat{msg}
		return true, err
	case 4: // check.check_spelling
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CheckSpelling)
		err := b.DecodeMessage(msg)
		m.Check = &Check_CheckSpelling{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Check_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Check)
	// check
	switch x := m.Check.(type) {
	case *Check_SoloKitGeneration:
		s := proto.Size(x.SoloKitGeneration)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Check_CodeGeneration:
		s := proto.Size(x.CodeGeneration)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Check_CheckFormat:
		s := proto.Size(x.CheckFormat)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Check_CheckSpelling:
		s := proto.Size(x.CheckSpelling)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CheckFormat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckFormat) Reset()         { *m = CheckFormat{} }
func (m *CheckFormat) String() string { return proto.CompactTextString(m) }
func (*CheckFormat) ProtoMessage()    {}
func (*CheckFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{21}
}
func (m *CheckFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckFormat.Unmarshal(m, b)
}
func (m *CheckFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckFormat.Marshal(b, m, deterministic)
}
func (m *CheckFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckFormat.Merge(m, src)
}
func (m *CheckFormat) XXX_Size() int {
	return xxx_messageInfo_CheckFormat.Size(m)
}
func (m *CheckFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckFormat.DiscardUnknown(m)
}

var xxx_messageInfo_CheckFormat proto.InternalMessageInfo

type CheckSpelling struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckSpelling) Reset()         { *m = CheckSpelling{} }
func (m *CheckSpelling) String() string { return proto.CompactTextString(m) }
func (*CheckSpelling) ProtoMessage()    {}
func (*CheckSpelling) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{22}
}
func (m *CheckSpelling) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckSpelling.Unmarshal(m, b)
}
func (m *CheckSpelling) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckSpelling.Marshal(b, m, deterministic)
}
func (m *CheckSpelling) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckSpelling.Merge(m, src)
}
func (m *CheckSpelling) XXX_Size() int {
	return xxx_messageInfo_CheckSpelling.Size(m)
}
func (m *CheckSpelling) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckSpelling.DiscardUnknown(m)
}

var xxx_messageInfo_CheckSpelling proto.InternalMessageInfo

type Docs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Docs) Reset()         { *m = Docs{} }
func (m *Docs) String() string { return proto.CompactTextString(m) }
func (*Docs) ProtoMessage()    {}
func (*Docs) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{23}
}
func (m *Docs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Docs.Unmarshal(m, b)
}
func (m *Docs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Docs.Marshal(b, m, deterministic)
}
func (m *Docs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Docs.Merge(m, src)
}
func (m *Docs) XXX_Size() int {
	return xxx_messageInfo_Docs.Size(m)
}
func (m *Docs) XXX_DiscardUnknown() {
	xxx_messageInfo_Docs.DiscardUnknown(m)
}

var xxx_messageInfo_Docs proto.InternalMessageInfo

type Distribution struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Distribution) Reset()         { *m = Distribution{} }
func (m *Distribution) String() string { return proto.CompactTextString(m) }
func (*Distribution) ProtoMessage()    {}
func (*Distribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_05c5040d8276e5da, []int{24}
}
func (m *Distribution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Distribution.Unmarshal(m, b)
}
func (m *Distribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Distribution.Marshal(b, m, deterministic)
}
func (m *Distribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distribution.Merge(m, src)
}
func (m *Distribution) XXX_Size() int {
	return xxx_messageInfo_Distribution.Size(m)
}
func (m *Distribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Distribution.DiscardUnknown(m)
}

var xxx_messageInfo_Distribution proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BuildRun)(nil), "build.solo.io.BuildRun")
	proto.RegisterType((*BuildRunConfig)(nil), "build.solo.io.BuildRunConfig")
	proto.RegisterType((*BuildEnvVars)(nil), "build.solo.io.BuildEnvVars")
	proto.RegisterType((*ComputedBuildVars)(nil), "build.solo.io.ComputedBuildVars")
	proto.RegisterType((*GcloudConfig)(nil), "build.solo.io.GcloudConfig")
	proto.RegisterType((*BuildSpec)(nil), "build.solo.io.BuildSpec")
	proto.RegisterType((*Manifest)(nil), "build.solo.io.Manifest")
	proto.RegisterType((*HelmChart)(nil), "build.solo.io.HelmChart")
	proto.RegisterType((*GoCompile)(nil), "build.solo.io.GoCompile")
	proto.RegisterType((*Compile)(nil), "build.solo.io.Compile")
	proto.RegisterType((*YarnCompile)(nil), "build.solo.io.YarnCompile")
	proto.RegisterType((*Container)(nil), "build.solo.io.Container")
	proto.RegisterType((*BuildConfig)(nil), "build.solo.io.BuildConfig")
	proto.RegisterType((*ContainerRegistry)(nil), "build.solo.io.ContainerRegistry")
	proto.RegisterType((*QuayRegistry)(nil), "build.solo.io.QuayRegistry")
	proto.RegisterType((*DockerHubRegistry)(nil), "build.solo.io.DockerHubRegistry")
	proto.RegisterType((*GoogleContainerRegistry)(nil), "build.solo.io.GoogleContainerRegistry")
	proto.RegisterType((*TestRun)(nil), "build.solo.io.TestRun")
	proto.RegisterMapType((map[string]string)(nil), "build.solo.io.TestRun.EnvEntry")
	proto.RegisterType((*CodeGeneration)(nil), "build.solo.io.CodeGeneration")
	proto.RegisterType((*SoloKitGeneration)(nil), "build.solo.io.SoloKitGeneration")
	proto.RegisterType((*Check)(nil), "build.solo.io.Check")
	proto.RegisterType((*CheckFormat)(nil), "build.solo.io.CheckFormat")
	proto.RegisterType((*CheckSpelling)(nil), "build.solo.io.CheckSpelling")
	proto.RegisterType((*Docs)(nil), "build.solo.io.Docs")
	proto.RegisterType((*Distribution)(nil), "build.solo.io.Distribution")
}

func init() { proto.RegisterFile("api/v1/build.proto", fileDescriptor_05c5040d8276e5da) }

var fileDescriptor_05c5040d8276e5da = []byte{
	// 1315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x4d, 0x73, 0xdb, 0x36,
	0x13, 0xd6, 0x97, 0x2d, 0x71, 0x25, 0xcb, 0x16, 0xec, 0xf7, 0x0d, 0xf3, 0xd5, 0xa4, 0x3c, 0x34,
	0x69, 0x93, 0x71, 0x62, 0x67, 0xd2, 0x64, 0x32, 0xed, 0x64, 0xe2, 0x8f, 0x58, 0x69, 0xa6, 0x4d,
	0x0a, 0xbb, 0x99, 0x49, 0x2f, 0x18, 0x88, 0x84, 0x29, 0x56, 0x14, 0xc1, 0x80, 0xa0, 0x66, 0x78,
	0xec, 0xad, 0xb7, 0xfe, 0x88, 0x4e, 0x2f, 0xbd, 0xf4, 0xd6, 0xdf, 0xd7, 0x01, 0x08, 0x4a, 0x94,
	0x44, 0xcf, 0xf4, 0x46, 0x3c, 0x78, 0x16, 0xbb, 0x58, 0xec, 0x3e, 0x4b, 0x40, 0x34, 0x0e, 0x1e,
	0xcd, 0x0e, 0x1e, 0x8d, 0xd2, 0x20, 0xf4, 0xf6, 0x63, 0xc1, 0x25, 0x47, 0x5b, 0xf9, 0x22, 0xe1,
	0x21, 0xdf, 0x0f, 0xb8, 0xc3, 0xa1, 0x73, 0xa4, 0x00, 0x9c, 0x46, 0xe8, 0x21, 0xb4, 0x92, 0x98,
	0xb9, 0x76, 0xfd, 0x6e, 0xfd, 0x7e, 0xf7, 0xd0, 0xde, 0x5f, 0x62, 0xee, 0x6b, 0xda, 0x79, 0xcc,
	0x5c, 0xac, 0x59, 0xe8, 0x29, 0x6c, 0xba, 0x3c, 0xba, 0x0c, 0x7c, 0xbb, 0xa1, 0xf9, 0xb7, 0xab,
	0xf8, 0x38, 0x8d, 0x8e, 0x35, 0x09, 0x1b, 0xb2, 0xf3, 0x67, 0x1d, 0xfa, 0xcb, 0x5b, 0xe8, 0x15,
	0xf4, 0xb5, 0x29, 0x61, 0xd1, 0x8c, 0xcc, 0xa8, 0x48, 0x4c, 0x04, 0x37, 0xab, 0x4e, 0x3c, 0x8d,
	0x66, 0x1f, 0xa8, 0x48, 0x70, 0x6f, 0x54, 0x5a, 0xa1, 0xf7, 0xb0, 0xeb, 0xf2, 0x69, 0x9c, 0x4a,
	0xe6, 0x91, 0xfc, 0x2c, 0x7d, 0x4e, 0x1e, 0xd9, 0xdd, 0x95, 0x73, 0x8e, 0x0d, 0x53, 0x9f, 0xa7,
	0x0f, 0x1b, 0xb8, 0xab, 0x90, 0x13, 0x40, 0xaf, 0xec, 0x0f, 0x5d, 0x87, 0x4e, 0x7e, 0x70, 0xe0,
	0xe9, 0xf0, 0x2c, 0xdc, 0xd6, 0xeb, 0x37, 0x1e, 0xba, 0x0d, 0xe0, 0xf2, 0xe9, 0x34, 0x90, 0x24,
	0x19, 0x53, 0xed, 0xd3, 0xc2, 0x56, 0x8e, 0x9c, 0x8f, 0x29, 0xba, 0x03, 0x5d, 0x49, 0x7d, 0x32,
	0x63, 0x22, 0x09, 0x78, 0x64, 0x37, 0xf5, 0x3e, 0x48, 0xea, 0x7f, 0xc8, 0x11, 0xe7, 0x3b, 0x18,
	0xac, 0x85, 0x84, 0x6c, 0x68, 0x0b, 0x16, 0x32, 0x9a, 0x30, 0xed, 0xae, 0x83, 0x8b, 0x25, 0xba,
	0x09, 0x56, 0x30, 0xa5, 0x3e, 0x23, 0x92, 0xfa, 0xc6, 0x5b, 0x47, 0x03, 0x17, 0xd4, 0x77, 0xfe,
	0xa8, 0x43, 0xef, 0xcc, 0x0d, 0x79, 0xea, 0x99, 0xe4, 0xde, 0x06, 0x88, 0x05, 0xff, 0x85, 0xb9,
	0x52, 0x45, 0xde, 0xca, 0x83, 0x33, 0xc8, 0x1b, 0x4f, 0x05, 0xe7, 0x31, 0x57, 0x64, 0xb1, 0x24,
	0x13, 0x96, 0xd9, 0x1b, 0x79, 0x70, 0x06, 0x7a, 0xcb, 0x32, 0x74, 0x0f, 0xb6, 0x4b, 0x04, 0x11,
	0x44, 0xbe, 0xbd, 0xa9, 0x49, 0xfd, 0x05, 0x49, 0xa1, 0xe8, 0x2b, 0x18, 0x8c, 0x59, 0x38, 0x25,
	0xee, 0x98, 0x0a, 0x49, 0x46, 0xa9, 0x3b, 0x61, 0xd2, 0x6e, 0x6b, 0xea, 0xb6, 0xda, 0x38, 0x56,
	0xf8, 0x91, 0x86, 0x9d, 0xbf, 0x9b, 0x60, 0xcd, 0xeb, 0x09, 0x1d, 0xce, 0x2b, 0x29, 0x7f, 0xf7,
	0x1b, 0x55, 0xef, 0xbe, 0x5c, 0x46, 0xe8, 0x21, 0x6c, 0xba, 0x63, 0xe6, 0x4e, 0xd4, 0x1b, 0x37,
	0xef, 0x77, 0x0f, 0xf7, 0x56, 0xdf, 0x58, 0x6d, 0x62, 0xc3, 0x41, 0x4f, 0xc1, 0x9a, 0xd2, 0x28,
	0xb8, 0x64, 0x89, 0x4c, 0xec, 0xa6, 0x36, 0xb8, 0xb6, 0x62, 0xf0, 0xbd, 0xd9, 0xc7, 0x0b, 0x26,
	0x7a, 0x0c, 0x6d, 0x55, 0x18, 0x41, 0xc8, 0xec, 0x96, 0x36, 0xfa, 0x7f, 0x45, 0x25, 0x05, 0x21,
	0xc3, 0x05, 0x0d, 0x3d, 0x01, 0x4b, 0xb2, 0x44, 0x12, 0x91, 0x46, 0x89, 0xbd, 0x51, 0x69, 0x73,
	0xa1, 0x9c, 0xa4, 0x11, 0xee, 0xc8, 0xfc, 0x23, 0x41, 0xcf, 0x55, 0xfd, 0x44, 0x92, 0x06, 0x11,
	0x13, 0x89, 0xbd, 0xa9, 0xad, 0xec, 0x35, 0x4f, 0x86, 0x80, 0x4b, 0x5c, 0x74, 0x0f, 0x5a, 0x1e,
	0x77, 0x13, 0x9d, 0xe6, 0xee, 0xe1, 0xee, 0x8a, 0xcd, 0x09, 0x77, 0x13, 0xac, 0x09, 0xe8, 0x25,
	0xf4, 0xbc, 0x20, 0x91, 0x22, 0x18, 0xa5, 0x52, 0x15, 0x61, 0xa7, 0xb2, 0xc1, 0x4e, 0x4a, 0x14,
	0xbc, 0x64, 0xe0, 0xbc, 0x86, 0x4e, 0x91, 0x21, 0xb4, 0x0f, 0x2d, 0xf5, 0xa0, 0x57, 0xe8, 0xc4,
	0xb0, 0x78, 0xeb, 0x61, 0x0d, 0x6b, 0xde, 0x11, 0x40, 0xa7, 0xc8, 0xa9, 0x83, 0xc1, 0x9a, 0x13,
	0x10, 0x82, 0x56, 0x44, 0xa7, 0xcc, 0xf4, 0x93, 0xfe, 0x46, 0x07, 0xf0, 0xbf, 0x34, 0x0e, 0x39,
	0xf5, 0x48, 0x46, 0xa7, 0x21, 0x91, 0x9c, 0xf8, 0x81, 0x1c, 0xa7, 0x23, 0x5d, 0xe9, 0x1d, 0x8c,
	0xf2, 0xcd, 0x8f, 0x74, 0x1a, 0x5e, 0xf0, 0x33, 0xbd, 0xe3, 0xfc, 0x56, 0x07, 0xeb, 0x8c, 0x9b,
	0xb7, 0xa8, 0x3c, 0xf4, 0x0e, 0x74, 0x59, 0x24, 0x45, 0x46, 0x62, 0x1e, 0x44, 0xd2, 0x34, 0x0d,
	0x68, 0xe8, 0xbd, 0x42, 0xd0, 0x2d, 0xb0, 0xe2, 0x90, 0xca, 0x4b, 0x2e, 0xa6, 0x79, 0x81, 0xa8,
	0x26, 0x29, 0x00, 0x74, 0x1f, 0x76, 0x4c, 0x4c, 0x8b, 0x70, 0x5a, 0x3a, 0x9c, 0x7e, 0x8e, 0xcf,
	0x43, 0xf9, 0xb5, 0x0e, 0xed, 0x22, 0x90, 0x67, 0x00, 0x3e, 0x27, 0x45, 0x01, 0xd5, 0x2b, 0x9f,
	0x75, 0x1e, 0x36, 0xb6, 0xfc, 0xf9, 0x0d, 0xbe, 0x85, 0x5e, 0x46, 0x45, 0x34, 0x37, 0x6d, 0x54,
	0x76, 0xc5, 0x47, 0x2a, 0xa2, 0xc2, 0xb8, 0x9b, 0x2d, 0x16, 0xce, 0x03, 0xe8, 0x96, 0xf6, 0xd4,
	0xd5, 0xbc, 0x40, 0x30, 0x57, 0x72, 0x91, 0x99, 0xa4, 0x2c, 0x00, 0xe7, 0x2d, 0x58, 0xf3, 0xd2,
	0x52, 0x5a, 0x91, 0x2b, 0x4b, 0x29, 0x81, 0xb9, 0xd6, 0xfc, 0x60, 0xb2, 0xe8, 0x71, 0x77, 0xc2,
	0x04, 0xb9, 0x2c, 0xc2, 0x52, 0x5a, 0xa1, 0xa1, 0xd7, 0xca, 0xf3, 0x5f, 0x0d, 0xe8, 0x96, 0x9a,
	0x55, 0x69, 0xa6, 0x60, 0x31, 0x27, 0x5c, 0xf8, 0x85, 0x66, 0xaa, 0xf5, 0x3b, 0xe1, 0x2b, 0x11,
	0xd3, 0x5b, 0xda, 0x93, 0x11, 0x31, 0x05, 0x68, 0x47, 0x5f, 0xc2, 0x0e, 0x4f, 0x65, 0x9c, 0x4a,
	0xb2, 0x88, 0x3c, 0x97, 0xcd, 0xed, 0x1c, 0x3f, 0x29, 0x60, 0x15, 0x93, 0x11, 0x56, 0xa5, 0xf8,
	0x46, 0xdf, 0xc0, 0x40, 0x1f, 0xa8, 0x50, 0x63, 0xca, 0xd7, 0x7a, 0x68, 0x43, 0x65, 0xcd, 0x97,
	0xc5, 0x72, 0x58, 0xc3, 0x86, 0x8c, 0xce, 0x61, 0x6f, 0xde, 0x67, 0x44, 0x30, 0x5f, 0xf7, 0x02,
	0x4b, 0xec, 0x3d, 0xfd, 0x8c, 0x77, 0xaf, 0xec, 0xce, 0x9c, 0x99, 0xe1, 0x5d, 0x77, 0x05, 0x0a,
	0x58, 0x72, 0xd4, 0x05, 0xcb, 0x0d, 0x88, 0x19, 0x84, 0xbf, 0x37, 0x94, 0xec, 0xaf, 0xd8, 0xe9,
	0x31, 0x43, 0x13, 0x46, 0x52, 0x11, 0xce, 0xc7, 0x0c, 0x4d, 0xd8, 0x4f, 0x22, 0x44, 0x9f, 0x43,
	0xcf, 0x8c, 0x00, 0xc2, 0xa3, 0x30, 0x33, 0x0d, 0xd1, 0x35, 0xd8, 0xbb, 0x28, 0xcc, 0xd0, 0x01,
	0xb4, 0x3e, 0xa5, 0x34, 0xbb, 0xe2, 0xaa, 0x3f, 0xa6, 0x34, 0x2b, 0x1c, 0xa9, 0xe6, 0x54, 0x54,
	0xf4, 0x0a, 0xcc, 0x0b, 0x12, 0x55, 0xd5, 0xdd, 0xca, 0x81, 0x79, 0xa2, 0x09, 0xc3, 0x74, 0x54,
	0xb2, 0xb6, 0xbc, 0x02, 0x44, 0x2f, 0xa0, 0xe9, 0xbb, 0xc2, 0xee, 0x69, 0xdb, 0x2f, 0xd6, 0x2a,
	0x9c, 0xfb, 0x21, 0x5b, 0xbb, 0xe8, 0xb0, 0x86, 0x95, 0x91, 0xd2, 0x06, 0x93, 0xdd, 0xcc, 0x79,
	0x06, 0xbd, 0x72, 0x88, 0x6a, 0xf4, 0xb0, 0x48, 0xcf, 0x18, 0xa6, 0x3a, 0x6f, 0xc2, 0x22, 0x93,
	0x92, 0xfe, 0x1c, 0xbe, 0x50, 0xa8, 0xf3, 0x0d, 0x0c, 0xd6, 0x42, 0xfc, 0xef, 0xd6, 0xd7, 0xe1,
	0xda, 0x15, 0x41, 0x2a, 0x65, 0x69, 0x1b, 0xbd, 0x56, 0xba, 0x42, 0x85, 0x9f, 0xe8, 0x46, 0xb6,
	0xb0, 0xfe, 0x46, 0x07, 0xd0, 0x64, 0xd1, 0xcc, 0x8c, 0xa0, 0x3b, 0xd5, 0x42, 0xbf, 0x7f, 0x1a,
	0xcd, 0x4e, 0x95, 0xd2, 0x60, 0xc5, 0xbd, 0xf1, 0x35, 0x74, 0x0a, 0x00, 0xed, 0x40, 0x53, 0x0d,
	0xdd, 0x3c, 0x2c, 0xf5, 0x89, 0xf6, 0x60, 0x63, 0x46, 0xc3, 0xb4, 0x68, 0x89, 0x7c, 0xf1, 0xa2,
	0xf1, 0xbc, 0xee, 0x3c, 0x86, 0xfe, 0x31, 0xf7, 0xd8, 0x19, 0x8b, 0x98, 0xa0, 0x4a, 0x92, 0xd1,
	0x67, 0x90, 0x2b, 0x58, 0xae, 0x69, 0xf5, 0x92, 0xa6, 0x69, 0xc4, 0xf9, 0x04, 0x83, 0x73, 0x1e,
	0xf2, 0xb7, 0x81, 0x2c, 0x19, 0x3d, 0x80, 0xc1, 0x94, 0x4e, 0x18, 0xf1, 0x58, 0xcc, 0x22, 0x8f,
	0x45, 0xae, 0x2a, 0xea, 0x86, 0xbe, 0xd2, 0x8e, 0xda, 0x38, 0x29, 0xe1, 0xe8, 0x11, 0xec, 0xfa,
	0x3c, 0xa6, 0x72, 0xbc, 0x4c, 0xcf, 0xf5, 0x11, 0xe5, 0x5b, 0x65, 0x03, 0xe7, 0x9f, 0x06, 0x6c,
	0xe8, 0xc9, 0x8b, 0x30, 0xec, 0xaa, 0x3c, 0x90, 0x49, 0x20, 0x89, 0x3f, 0x77, 0x6f, 0x46, 0xc6,
	0x6a, 0x7d, 0xad, 0x85, 0x39, 0xac, 0xe1, 0x41, 0xb2, 0x16, 0xfb, 0x10, 0xb6, 0x5d, 0xee, 0xb1,
	0xf2, 0x79, 0xd5, 0xbf, 0x9e, 0xcb, 0x89, 0x1a, 0xd6, 0x70, 0xdf, 0x5d, 0x4e, 0xdd, 0x4b, 0xe8,
	0xe9, 0x3f, 0x03, 0xa2, 0xf4, 0x9d, 0x4a, 0x2d, 0x2e, 0xeb, 0x0a, 0xab, 0x6f, 0xf2, 0x5a, 0x33,
	0x86, 0x35, 0xdc, 0x75, 0x17, 0x4b, 0x74, 0x0a, 0xfd, 0xfc, 0x80, 0x24, 0x66, 0x61, 0xa8, 0x7e,
	0x8a, 0x5a, 0xfa, 0x88, 0x5b, 0x55, 0x47, 0x9c, 0x1b, 0xce, 0xb0, 0x86, 0xb7, 0xdc, 0x32, 0x70,
	0xd4, 0x86, 0x0d, 0x0d, 0x38, 0x5b, 0xd0, 0x2d, 0x79, 0x73, 0xb6, 0x61, 0x6b, 0xc9, 0xd2, 0xd9,
	0x84, 0x96, 0x9a, 0xe6, 0x4e, 0x1f, 0x7a, 0xe5, 0x21, 0x7d, 0xd4, 0xfa, 0xb9, 0x31, 0x3b, 0x18,
	0x6d, 0xea, 0x5f, 0xfb, 0x27, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x32, 0xa8, 0xfb, 0xf0,
	0x0b, 0x00, 0x00,
}
